### ISSUE TITLE
Output value in uTesta or uGauss

### ISSUE THREAD

**Issue by brightproject** [keepworking/Mecha_QMC5883L#7]
Hello @keepworking 
What values do we get at the library output?
```
  int x,y,z;
  qmc.read(&x,&y,&z);

  Serial.print("x: ");
  Serial.print(x);
  Serial.print(" y: ");
  Serial.print(y);
  Serial.print(" z: ");
  Serial.print(z);
  Serial.println();
  delay(100);
```
Judging by the library code, these are raw values without scaling and conversion to units of magnetic field strength.
```
int MechaQMC5883::read(int* x,int* y,int* z){
   Wire.beginTransmission(address);
   Wire.write(0x00);
   int err = Wire.endTransmission();
   if (err) {return err;}
   Wire.requestFrom(address, 7);
   *x = (int)(int16_t)(Wire.read() | Wire.read() << 8);
   *y = (int)(int16_t)(Wire.read() | Wire.read() << 8);
   *z = (int)(int16_t)(Wire.read() | Wire.read() << 8);
   byte overflow = Wire.read() & 0x02;
   return overflow << 2;
}
```
But the output is very small values, similar to `uTesla`.

**Comment by keepworking** [comment]
The value read as byte is a relative value of the actual number.

That value is the value coming from the ADC in the sensor. It varies depending on the set scale.

The default setting will be 8G scale, which will be -8G to 8G.

Since it is a 16-bit value, it is in the range of -32,768 to 32,767.

You can think of -32,768 as being around -8G.

It's been a while since I made it, so my memory is unclear, but it might be helpful to refer to the data sheet.
